title:               "LIZP: Learn/Implement/Zone/Practice"
url:                 https://blogs.lizmore.dev
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Liz
