title:               "LizP: Learn iz Practice"
url:                 https://blogs.lizmore.dev
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Liz

plugins: [jekyll-paginate]
